import { WhatsAppIcon } from '../../components/icons/WhatsAppIcon';
import { SEO } from '../../components/SEO';
import { Link } from 'react-router-dom';
import { CheckCircle2, PhoneCall, ArrowRight, Camera, Shield, Eye, Monitor } from 'lucide-react';

export default function CctvInstallation() {
    const faqData = [
        { q: "How much does CCTV installation cost in Riyadh?", a: "Costs vary based on the number of cameras, type of system, and facility size. Contact us for a free on-site assessment and quotation." },
        { q: "Do you install indoor and outdoor cameras?", a: "Yes. We install a full range of indoor, outdoor, dome, bullet, and PTZ security cameras suited for homes, offices, and commercial properties." },
        { q: "Can I monitor cameras remotely?", a: "Absolutely. We configure remote viewing on your smartphone, tablet, or PC so you can monitor your property from anywhere, anytime." },
        { q: "Do you provide maintenance for CCTV systems?", a: "Yes, we offer regular maintenance contracts including camera cleaning, firmware updates, DVR/NVR checks, and hardware replacement." },
        { q: "What areas in Riyadh do you cover?", a: "We cover all major districts including Olaya, Al Malaz, Al Nakheel, Al Yasmin, Al Murabba, and surrounding areas." }
    ];
    const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqData.map(f => ({ "@type": "Question", "name": f.q, "acceptedAnswer": { "@type": "Answer", "text": f.a } })) };

    return (
        <>
            <SEO title="CCTV Installation in Riyadh | Security Camera Systems | Perfect Energy Solution" description="Professional CCTV installation in Riyadh for homes and businesses. Reliable security systems with expert setup. Contact Perfect Energy Solution today." canonicalUrl="/services/cctv-installation"
                jsonLdSchema={[faqSchema, { "@context": "https://schema.org", "@type": "Service", "serviceType": "CCTV Installation", "provider": { "@type": "LocalBusiness", "name": "Perfect Energy Solution" }, "areaServed": { "@type": "City", "name": "Riyadh" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://perfectenergysolution.com" }, { "@type": "ListItem", "position": 2, "name": "Services", "item": "https://perfectenergysolution.com/services" }, { "@type": "ListItem", "position": 3, "name": "CCTV Installation" }] }]} />
            <div className="flex flex-col min-h-screen bg-background">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl pt-8"><nav className="flex items-center gap-2 text-sm text-gray-500 font-sans"><Link to="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link to="/services" className="hover:text-accent transition-colors">Services</Link><span>/</span><span className="text-textDark font-medium">CCTV & Security Systems</span></nav></div>
                <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-12 lg:py-16">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-sm font-medium mb-6"><Camera className="w-4 h-4" /> Security Solutions</div>
                            <h1 className="text-4xl md:text-5xl font-heading font-extrabold text-textDark leading-tight mb-6">CCTV & Security Systems Installation in <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-accent">Riyadh</span></h1>
                            <p className="text-lg text-textDark/70 font-sans leading-relaxed mb-4">Protect your property with professional CCTV installation services from Perfect Energy Solution in Riyadh. We design and install customized surveillance and security camera systems for homes, offices, retail stores, and commercial facilities — giving you complete peace of mind with 24/7 monitoring capability.</p>
                            <p className="text-base text-gray-500 font-sans leading-relaxed mb-8">Our certified technicians assess your security needs and recommend the optimal camera placement, system type, and remote monitoring setup to maximize coverage and deter threats effectively.</p>
                            <div className="flex flex-col sm:flex-row gap-4">
                                <a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-semibold transition-all shadow-lg transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Get a Free Assessment</a>
                                <a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white hover:bg-gray-50 text-primary border border-borderGrey px-8 py-4 rounded-xl font-semibold transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5 text-green-500" /> WhatsApp Us</a>
                            </div>
                        </div>
                        <div className="bg-primary rounded-3xl p-10 text-white relative overflow-hidden">
                            <div className="absolute -top-20 -right-20 w-40 h-40 bg-accent/20 rounded-full blur-3xl pointer-events-none"></div>
                            <h3 className="text-xl font-heading font-bold text-white mb-6">What We Install</h3>
                            <ul className="space-y-3">{["HD & 4K security cameras", "Indoor & outdoor systems", "Night vision cameras", "DVR/NVR recording systems", "Remote mobile monitoring", "Access control systems"].map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-200"><CheckCircle2 className="w-5 h-5 text-accent shrink-0" /> {item}</li>))}</ul>
                        </div>
                    </div>
                </section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Our Security Services</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{[{ icon: Camera, title: "CCTV Camera Installation", items: ["Site survey & planning", "Camera mounting & wiring", "DVR/NVR setup & storage", "System testing & handover"] }, { icon: Eye, title: "Remote Monitoring Setup", items: ["Smartphone app configuration", "PC/tablet live view setup", "Cloud storage integration", "Multi-location monitoring"] }, { icon: Shield, title: "Security System Upgrades", items: ["Analog to IP upgrades", "Camera resolution upgrades", "Storage capacity expansion", "New camera additions"] }, { icon: Monitor, title: "Maintenance & Support", items: ["Preventive maintenance", "Camera lens cleaning", "Firmware & software updates", "24/7 support availability"] }].map((s, idx) => (<div key={idx} className="bg-background rounded-3xl p-8 border border-borderGrey"><div className="flex items-center gap-4 mb-6"><div className="w-12 h-12 rounded-2xl bg-accent/10 flex items-center justify-center text-accent"><s.icon className="w-6 h-6" /></div><h3 className="text-xl font-heading font-bold text-textDark">{s.title}</h3></div><ul className="space-y-2">{s.items.map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-600 font-sans"><CheckCircle2 className="w-4 h-4 text-accent shrink-0" /> {item}</li>))}</ul></div>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Our Installation Process</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6">{[{ num: "01", title: "Site Survey", desc: "Assess your property for optimal camera placement." }, { num: "02", title: "System Design", desc: "Custom security plan based on your specific needs." }, { num: "03", title: "Installation", desc: "Professional mounting, wiring, and configuration." }, { num: "04", title: "Configuration", desc: "Remote access, recording, and alerts setup." }, { num: "05", title: "Training", desc: "Complete walkthrough of your security system." }].map((step, idx) => (<div key={idx} className="bg-white rounded-3xl p-6 border border-borderGrey text-center group hover:shadow-md transition-all"><div className="w-12 h-12 bg-accent/10 rounded-2xl flex items-center justify-center text-accent mx-auto mb-4 font-heading font-bold text-lg group-hover:scale-110 transition-transform">{step.num}</div><h3 className="text-lg font-heading font-bold text-textDark mb-2">{step.title}</h3><p className="text-gray-600 font-sans text-sm leading-relaxed">{step.desc}</p></div>))}</div></div></section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl text-center"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-6">CCTV Installation Services Across Riyadh</h2><p className="text-lg text-gray-600 font-sans max-w-3xl mx-auto mb-10">We install security systems across all major Riyadh areas:</p><div className="flex flex-wrap justify-center gap-3">{["Olaya", "Al Malaz", "Al Nakheel", "Al Yasmin", "Al Murabba", "King Fahd District", "Al Worood", "Al Rawdah", "Al Sulimaniyah"].map((a, i) => (<span key={i} className="px-4 py-2 bg-accent/10 text-accent rounded-full font-semibold text-sm border border-accent/20">{a}</span>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl font-heading font-extrabold text-textDark mb-12 text-center">Trusted Security Experts in Riyadh</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">{[{ value: "15+", label: "Years Experience" }, { value: "2000+", label: "Systems Installed" }, { value: "99%", label: "Client Retention" }, { value: "24/7", label: "Support Available" }].map((s, i) => (<div key={i} className="bg-white rounded-3xl p-8 border border-borderGrey shadow-sm"><div className="text-3xl font-heading font-bold text-accent mb-2">{s.value}</div><div className="text-gray-600 font-sans text-sm">{s.label}</div></div>))}</div></div></section>
                <section className="bg-white py-16"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-2xl font-heading font-bold text-textDark mb-8 text-center">Explore Related Services</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[{ title: "Networking Solutions", slug: "networking-solutions", desc: "Office network setup and IT support." }, { title: "Electrical Services", slug: "electrical-services", desc: "Electrical installation and maintenance." }, { title: "Electronics Repair", slug: "electronics-repair", desc: "Device repair and diagnostics." }].map((link, idx) => (<Link key={idx} to={`/services/${link.slug}`} className="flex items-center justify-between p-6 bg-background rounded-2xl border border-borderGrey hover:border-accent/30 transition-colors group"><div><h3 className="font-heading font-bold text-textDark mb-1">{link.title}</h3><p className="text-sm text-gray-500">{link.desc}</p></div><ArrowRight className="w-5 h-5 text-accent opacity-0 group-hover:opacity-100 transition-opacity" /></Link>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-4">{faqData.map((faq, idx) => (<details key={idx} className="bg-white rounded-2xl border border-borderGrey p-6 group"><summary className="font-heading font-bold text-textDark cursor-pointer list-none flex items-center justify-between">{faq.q}<span className="text-accent text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-gray-600 font-sans mt-4 leading-relaxed">{faq.a}</p></details>))}</div></div></section>
                <section className="pb-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><div className="bg-primary rounded-3xl p-10 md:p-16 text-center relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-accent/20 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div><div className="relative z-10 max-w-2xl mx-auto"><h2 className="text-3xl md:text-4xl font-heading font-bold text-white mb-4">Secure Your Property Today</h2><p className="text-gray-300 font-sans text-lg mb-8">Get a free security assessment and professional CCTV installation quote.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition-all transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Now</a><a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 font-semibold px-8 py-4 rounded-xl transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5" /> WhatsApp Us</a></div></div></div></div></section>
            </div>
        </>
    );
}
