import { WhatsAppIcon } from '../../components/icons/WhatsAppIcon';
import { SEO } from '../../components/SEO';
import { Link } from 'react-router-dom';
import { CheckCircle2, PhoneCall, ArrowRight, Zap, Lightbulb, Power, Plug } from 'lucide-react';

export default function ElectricalServices() {
    const faqData = [
        { q: "What electrical services do you offer?", a: "We offer electrical installation, wiring, fault detection and repair, electrical system upgrades, lighting installation, and preventive maintenance for homes and businesses." },
        { q: "Are your electricians certified?", a: "Yes. Our electricians are fully trained and experienced, following industry safety standards for all electrical work in Riyadh." },
        { q: "Do you handle commercial electrical projects?", a: "Absolutely. We serve both residential and commercial clients, including offices, retail stores, warehouses, and large facilities." },
        { q: "How quickly can you respond to an electrical emergency?", a: "We aim to respond to urgent electrical issues within the same day. Contact us immediately for emergency electrical support." },
        { q: "Do you provide electrical maintenance contracts?", a: "Yes, we offer scheduled maintenance contracts to keep your electrical systems safe, efficient, and compliant." }
    ];
    const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqData.map(f => ({ "@type": "Question", "name": f.q, "acceptedAnswer": { "@type": "Answer", "text": f.a } })) };

    return (
        <>
            <SEO title="Electrical Services in Riyadh | Installation & Maintenance | Perfect Energy Solution" description="Professional electrical installation, maintenance, and repair services in Riyadh. Certified electricians for homes and businesses. Contact Perfect Energy Solution." canonicalUrl="/services/electrical-services"
                jsonLdSchema={[faqSchema, { "@context": "https://schema.org", "@type": "Service", "serviceType": "Electrical Services", "provider": { "@type": "LocalBusiness", "name": "Perfect Energy Solution" }, "areaServed": { "@type": "City", "name": "Riyadh" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://perfectenergysolution.com" }, { "@type": "ListItem", "position": 2, "name": "Services", "item": "https://perfectenergysolution.com/services" }, { "@type": "ListItem", "position": 3, "name": "Electrical Services" }] }]} />
            <div className="flex flex-col min-h-screen bg-background">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl pt-8"><nav className="flex items-center gap-2 text-sm text-gray-500 font-sans"><Link to="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link to="/services" className="hover:text-accent transition-colors">Services</Link><span>/</span><span className="text-textDark font-medium">Electrical Services</span></nav></div>
                <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-12 lg:py-16">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-400/10 border border-amber-400/20 text-amber-600 text-sm font-medium mb-6"><Zap className="w-4 h-4" /> Professional Electricians</div>
                            <h1 className="text-4xl md:text-5xl font-heading font-extrabold text-textDark leading-tight mb-6">Electrical Services in <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-accent">Riyadh</span></h1>
                            <p className="text-lg text-textDark/70 font-sans leading-relaxed mb-4">Perfect Energy Solution provides professional electrical installation, maintenance, and repair services across Riyadh. Our experienced electricians deliver safe, reliable, and code-compliant electrical work for residential homes, offices, retail stores, and large commercial facilities.</p>
                            <p className="text-base text-gray-500 font-sans leading-relaxed mb-8">From new wiring installations and circuit breaker upgrades to emergency fault repairs and scheduled maintenance programs — we handle all aspects of electrical service with precision and safety.</p>
                            <div className="flex flex-col sm:flex-row gap-4">
                                <a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-semibold transition-all shadow-lg transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Request Service</a>
                                <a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white hover:bg-gray-50 text-primary border border-borderGrey px-8 py-4 rounded-xl font-semibold transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5 text-green-500" /> WhatsApp Us</a>
                            </div>
                        </div>
                        <div className="space-y-6 lg:ml-10">
                            <div className="w-full aspect-square bg-gray-50 rounded-[2.5rem] border border-borderGrey overflow-hidden shadow-sm relative group">
                                <img src="/electrical_services.webp" alt="Electrical Services" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-1000" />
                            </div>
                            <div className="bg-primary rounded-[2rem] p-8 text-white relative overflow-hidden shadow-sm">
                                <div className="absolute -top-20 -right-20 w-40 h-40 bg-accent/20 rounded-full blur-3xl pointer-events-none"></div>
                                <h3 className="text-lg font-heading font-bold text-white mb-4">Our Electrical Services</h3>
                                <ul className="space-y-2">{["New electrical installations", "Wiring & rewiring", "Circuit breaker upgrades", "Lighting installations", "Fault detection & repair", "Preventive maintenance"].map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-200 text-sm"><CheckCircle2 className="w-4 h-4 text-accent shrink-0" /> {item}</li>))}</ul>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Our Electrical Service Areas</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{[{ icon: Plug, title: "Installation & Wiring", items: ["Complete electrical installations", "Structured wiring systems", "Power outlet and switch installation", "Distribution board setup"] }, { icon: Lightbulb, title: "Lighting Solutions", items: ["Interior & exterior lighting", "LED retrofit installations", "Emergency lighting systems", "Smart lighting controls"] }, { icon: Power, title: "Power Distribution", items: ["Circuit breaker installation", "Load balancing & optimization", "Backup power systems", "Voltage stabilization"] }, { icon: Zap, title: "Repair & Maintenance", items: ["Electrical fault diagnosis", "Short circuit repair", "Scheduled maintenance", "Safety inspections"] }].map((s, idx) => (<div key={idx} className="bg-background rounded-3xl p-8 border border-borderGrey"><div className="flex items-center gap-4 mb-6"><div className="w-12 h-12 rounded-2xl bg-amber-400/10 flex items-center justify-center text-amber-500"><s.icon className="w-6 h-6" /></div><h3 className="text-xl font-heading font-bold text-textDark">{s.title}</h3></div><ul className="space-y-2">{s.items.map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-600 font-sans"><CheckCircle2 className="w-4 h-4 text-amber-500 shrink-0" /> {item}</li>))}</ul></div>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl text-center"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-6">Electrical Services Across Riyadh</h2><p className="text-lg text-gray-600 font-sans max-w-3xl mx-auto mb-10">We provide electrical services across all districts in Riyadh:</p><div className="flex flex-wrap justify-center gap-3">{["Olaya", "Al Malaz", "Al Nakheel", "Al Yasmin", "Al Murabba", "King Fahd District", "Al Worood"].map((a, i) => (<span key={i} className="px-4 py-2 bg-accent/10 text-accent rounded-full font-semibold text-sm border border-accent/20">{a}</span>))}</div></div></section>
                <section className="bg-white py-16"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-2xl font-heading font-bold text-textDark mb-8 text-center">Explore Related Services</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[{ title: "SIM Card Services", slug: "sim-card-services", desc: "SIM activation, recharge, and plans." }, { title: "Electronics Repair", slug: "electronics-repair", desc: "Device diagnostics and repair." }, { title: "CCTV Installation", slug: "cctv-installation", desc: "Security camera systems." }].map((link, idx) => (<Link key={idx} to={`/services/${link.slug}`} className="flex items-center justify-between p-6 bg-background rounded-2xl border border-borderGrey hover:border-accent/30 transition-colors group"><div><h3 className="font-heading font-bold text-textDark mb-1">{link.title}</h3><p className="text-sm text-gray-500">{link.desc}</p></div><ArrowRight className="w-5 h-5 text-accent opacity-0 group-hover:opacity-100 transition-opacity" /></Link>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-4">{faqData.map((faq, idx) => (<details key={idx} className="bg-white rounded-2xl border border-borderGrey p-6 group"><summary className="font-heading font-bold text-textDark cursor-pointer list-none flex items-center justify-between">{faq.q}<span className="text-accent text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-gray-600 font-sans mt-4 leading-relaxed">{faq.a}</p></details>))}</div></div></section>
                <section className="pb-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><div className="bg-primary rounded-3xl p-10 md:p-16 text-center relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-accent/20 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div><div className="relative z-10 max-w-2xl mx-auto"><h2 className="text-3xl md:text-4xl font-heading font-bold text-white mb-4">Need an Electrician in Riyadh?</h2><p className="text-gray-300 font-sans text-lg mb-8">Our certified electricians are ready to help with any electrical project.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition-all transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Now</a><a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 font-semibold px-8 py-4 rounded-xl transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5" /> WhatsApp Us</a></div></div></div></div></section>
            </div>
        </>
    );
}
