import { WhatsAppIcon } from '../../components/icons/WhatsAppIcon';
import { SEO } from '../../components/SEO';
import { Link } from 'react-router-dom';
import { CheckCircle2, PhoneCall, ArrowRight, Sun, Battery, Gauge, Leaf } from 'lucide-react';

export default function SolarSolutions() {
    const faqData = [
        { q: "How much does solar panel installation cost in Riyadh?", a: "Costs depend on system size, panel type, and property specifications. We offer free on-site assessments and competitive quotes for all residential and commercial projects." },
        { q: "How long does solar panel installation take?", a: "A typical residential installation takes 2–5 days. Commercial projects may take 1–3 weeks depending on scale and complexity." },
        { q: "Will solar panels work in Riyadh's climate?", a: "Absolutely. Riyadh's abundant sunshine makes it one of the best locations globally for solar energy production. Solar panels perform excellently in Saudi Arabia's high-sunlight conditions." },
        { q: "Do you handle permits and approvals?", a: "Yes. We assist with all necessary permits, approvals, and regulatory compliance for solar installations in Saudi Arabia." },
        { q: "What maintenance do solar panels need?", a: "Solar panels require minimal maintenance — mainly periodic cleaning and annual inspections. We offer maintenance contracts to ensure optimal performance." }
    ];
    const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqData.map(f => ({ "@type": "Question", "name": f.q, "acceptedAnswer": { "@type": "Answer", "text": f.a } })) };

    return (
        <>
            <SEO title="Solar Panel Installation in Riyadh | Solar Energy Solutions | Perfect Energy Solution" description="Professional solar panel installation and energy solutions in Riyadh. Reduce electricity bills with sustainable solar systems. Free assessment available." canonicalUrl="/services/solar-solutions"
                jsonLdSchema={[faqSchema, { "@context": "https://schema.org", "@type": "Service", "serviceType": "Solar Panel Installation", "provider": { "@type": "LocalBusiness", "name": "Perfect Energy Solution" }, "areaServed": { "@type": "City", "name": "Riyadh" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://perfectenergysolution.com" }, { "@type": "ListItem", "position": 2, "name": "Services", "item": "https://perfectenergysolution.com/services" }, { "@type": "ListItem", "position": 3, "name": "Solar Solutions" }] }]} />
            <div className="flex flex-col min-h-screen bg-background">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl pt-8"><nav className="flex items-center gap-2 text-sm text-gray-500 font-sans"><Link to="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link to="/services" className="hover:text-accent transition-colors">Services</Link><span>/</span><span className="text-textDark font-medium">Solar & Energy Solutions</span></nav></div>
                <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-12 lg:py-16">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-yellow-500/10 border border-yellow-500/20 text-yellow-600 text-sm font-medium mb-6"><Sun className="w-4 h-4" /> Sustainable Energy</div>
                            <h1 className="text-4xl md:text-5xl font-heading font-extrabold text-textDark leading-tight mb-6">Solar & Energy Solutions in <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-accent">Riyadh</span></h1>
                            <p className="text-lg text-textDark/70 font-sans leading-relaxed mb-4">Perfect Energy Solution delivers professional solar panel installation and energy management services throughout Riyadh and Saudi Arabia. Harness the Kingdom's abundant sunshine to reduce your electricity bills, achieve energy independence, and contribute to a more sustainable future with our expertly designed solar systems.</p>
                            <p className="text-base text-gray-500 font-sans leading-relaxed mb-8">From residential rooftop installations to large-scale commercial solar projects, we handle every aspect — system design, procurement, installation, and ongoing maintenance — ensuring maximum energy output and return on investment.</p>
                            <div className="flex flex-col sm:flex-row gap-4">
                                <a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-semibold transition-all shadow-lg transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Get Free Assessment</a>
                                <a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white hover:bg-gray-50 text-primary border border-borderGrey px-8 py-4 rounded-xl font-semibold transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5 text-green-500" /> WhatsApp Us</a>
                            </div>
                        </div>
                        <div className="bg-primary rounded-3xl p-10 text-white relative overflow-hidden">
                            <div className="absolute -top-20 -right-20 w-40 h-40 bg-yellow-400/20 rounded-full blur-3xl pointer-events-none"></div>
                            <h3 className="text-xl font-heading font-bold text-white mb-6">Our Solar Services</h3>
                            <ul className="space-y-3">{["Solar panel installation", "System design & consultation", "Inverter setup & configuration", "Battery storage solutions", "Energy efficiency audits", "Maintenance & monitoring"].map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-200"><CheckCircle2 className="w-5 h-5 text-yellow-400 shrink-0" /> {item}</li>))}</ul>
                        </div>
                    </div>
                </section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Our Solar Energy Services</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{[{ icon: Sun, title: "Solar Panel Installation", items: ["Rooftop solar systems", "Ground-mounted solar arrays", "Commercial solar projects", "Residential solar installations"] }, { icon: Battery, title: "Battery & Storage Solutions", items: ["Lithium-ion battery systems", "Energy storage design", "Backup power systems", "Off-grid solutions"] }, { icon: Gauge, title: "Energy Efficiency", items: ["Energy consumption audits", "Smart energy monitoring", "Load optimization", "Cost reduction strategies"] }, { icon: Leaf, title: "Maintenance & Support", items: ["Panel cleaning & inspection", "Inverter maintenance", "Performance monitoring", "Warranty support"] }].map((s, idx) => (<div key={idx} className="bg-background rounded-3xl p-8 border border-borderGrey"><div className="flex items-center gap-4 mb-6"><div className="w-12 h-12 rounded-2xl bg-yellow-500/10 flex items-center justify-center text-yellow-500"><s.icon className="w-6 h-6" /></div><h3 className="text-xl font-heading font-bold text-textDark">{s.title}</h3></div><ul className="space-y-2">{s.items.map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-600 font-sans"><CheckCircle2 className="w-4 h-4 text-yellow-500 shrink-0" /> {item}</li>))}</ul></div>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Our Installation Process</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6">{[{ num: "01", title: "Consultation", desc: "Assess energy needs and site suitability." }, { num: "02", title: "System Design", desc: "Custom solar system designed for maximum output." }, { num: "03", title: "Procurement", desc: "Source premium panels and inverters." }, { num: "04", title: "Installation", desc: "Professional mounting, wiring, and connection." }, { num: "05", title: "Commissioning", desc: "Testing, monitoring setup, and handover." }].map((step, idx) => (<div key={idx} className="bg-white rounded-3xl p-6 border border-borderGrey text-center group hover:shadow-md transition-all"><div className="w-12 h-12 bg-yellow-500/10 rounded-2xl flex items-center justify-center text-yellow-500 mx-auto mb-4 font-heading font-bold text-lg group-hover:scale-110 transition-transform">{step.num}</div><h3 className="text-lg font-heading font-bold text-textDark mb-2">{step.title}</h3><p className="text-gray-600 font-sans text-sm leading-relaxed">{step.desc}</p></div>))}</div></div></section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl text-center"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-6">Solar Installation Across Riyadh</h2><p className="text-lg text-gray-600 font-sans max-w-3xl mx-auto mb-10">We install solar systems across all areas in Riyadh and Saudi Arabia:</p><div className="flex flex-wrap justify-center gap-3">{["Olaya", "Al Malaz", "Al Nakheel", "Al Yasmin", "Al Murabba", "King Fahd District", "Al Worood", "Al Rawdah"].map((a, i) => (<span key={i} className="px-4 py-2 bg-accent/10 text-accent rounded-full font-semibold text-sm border border-accent/20">{a}</span>))}</div></div></section>
                <section className="py-16"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-2xl font-heading font-bold text-textDark mb-8 text-center">Explore Related Services</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[{ title: "Electrical Services", slug: "electrical-services", desc: "Professional electrical installations." }, { title: "Electronics Repair", slug: "electronics-repair", desc: "Device repair and maintenance." }, { title: "Technical Support", slug: "technical-support", desc: "General technical assistance." }].map((link, idx) => (<Link key={idx} to={`/services/${link.slug}`} className="flex items-center justify-between p-6 bg-background rounded-2xl border border-borderGrey hover:border-accent/30 transition-colors group"><div><h3 className="font-heading font-bold text-textDark mb-1">{link.title}</h3><p className="text-sm text-gray-500">{link.desc}</p></div><ArrowRight className="w-5 h-5 text-accent opacity-0 group-hover:opacity-100 transition-opacity" /></Link>))}</div></div></section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-4">{faqData.map((faq, idx) => (<details key={idx} className="bg-background rounded-2xl border border-borderGrey p-6 group"><summary className="font-heading font-bold text-textDark cursor-pointer list-none flex items-center justify-between">{faq.q}<span className="text-accent text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-gray-600 font-sans mt-4 leading-relaxed">{faq.a}</p></details>))}</div></div></section>
                <section className="pb-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><div className="bg-primary rounded-3xl p-10 md:p-16 text-center relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-yellow-400/20 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div><div className="relative z-10 max-w-2xl mx-auto"><h2 className="text-3xl md:text-4xl font-heading font-bold text-white mb-4">Ready to Go Solar in Riyadh?</h2><p className="text-gray-300 font-sans text-lg mb-8">Get a free solar assessment and start saving on electricity bills today.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition-all transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Now</a><a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 font-semibold px-8 py-4 rounded-xl transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5" /> WhatsApp Us</a></div></div></div></div></section>
            </div>
        </>
    );
}
