import { WhatsAppIcon } from '../../components/icons/WhatsAppIcon';
import { SEO } from '../../components/SEO';
import { Link } from 'react-router-dom';
import { CheckCircle2, PhoneCall, ArrowRight, Wrench, Settings, HelpCircle, Headphones } from 'lucide-react';

export default function TechnicalSupport() {
    const faqData = [
        { q: "What kind of technical support do you provide?", a: "We provide comprehensive technical assistance including IT troubleshooting, equipment setup, system configuration, hardware repair, and on-site technical support for homes and businesses in Riyadh." },
        { q: "Do you offer on-site technical support?", a: "Yes. Our technicians come directly to your location in Riyadh for on-site diagnostics, repair, and setup services." },
        { q: "Can you help with office equipment setup?", a: "Absolutely. We handle all types of office equipment setup including printers, projectors, access control systems, and audiovisual equipment." },
        { q: "Do you offer support contracts?", a: "Yes, we provide flexible support contracts including monthly and annual plans for businesses that require regular technical assistance." },
        { q: "What areas in Riyadh do you serve?", a: "We serve all major areas across Riyadh including Olaya, Al Malaz, Al Nakheel, Al Yasmin, Al Murabba, and surrounding districts." }
    ];
    const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqData.map(f => ({ "@type": "Question", "name": f.q, "acceptedAnswer": { "@type": "Answer", "text": f.a } })) };

    return (
        <>
            <SEO title="Technical Support Services in Riyadh | Expert IT Assistance | Perfect Energy Solution" description="Reliable technical support and IT assistance in Riyadh. On-site troubleshooting, equipment setup, and maintenance for homes and businesses." canonicalUrl="/services/technical-support"
                jsonLdSchema={[faqSchema, { "@context": "https://schema.org", "@type": "Service", "serviceType": "Technical Support", "provider": { "@type": "LocalBusiness", "name": "Perfect Energy Solution" }, "areaServed": { "@type": "City", "name": "Riyadh" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://perfectenergysolution.com" }, { "@type": "ListItem", "position": 2, "name": "Services", "item": "https://perfectenergysolution.com/services" }, { "@type": "ListItem", "position": 3, "name": "Technical Support" }] }]} />
            <div className="flex flex-col min-h-screen bg-background">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl pt-8"><nav className="flex items-center gap-2 text-sm text-gray-500 font-sans"><Link to="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link to="/services" className="hover:text-accent transition-colors">Services</Link><span>/</span><span className="text-textDark font-medium">General Technical Services</span></nav></div>
                <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-12 lg:py-16">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 text-sm font-medium mb-6"><Wrench className="w-4 h-4" /> Reliable Support</div>
                            <h1 className="text-4xl md:text-5xl font-heading font-extrabold text-textDark leading-tight mb-6">General Technical Support Services in <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-accent">Riyadh</span></h1>
                            <p className="text-lg text-textDark/70 font-sans leading-relaxed mb-4">Perfect Energy Solution provides dependable general technical support and IT assistance across Riyadh. Whether you need on-site troubleshooting, equipment installation, system configuration, or regular maintenance — our experienced technicians solve your technical challenges quickly and efficiently.</p>
                            <p className="text-base text-gray-500 font-sans leading-relaxed mb-8">We serve residential homes, small businesses, offices, and commercial facilities, offering both one-time support and ongoing maintenance contracts tailored to your specific needs.</p>
                            <div className="flex flex-col sm:flex-row gap-4">
                                <a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-semibold transition-all shadow-lg transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Get Support Now</a>
                                <a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white hover:bg-gray-50 text-primary border border-borderGrey px-8 py-4 rounded-xl font-semibold transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5 text-green-500" /> WhatsApp Us</a>
                            </div>
                        </div>
                        <div className="bg-primary rounded-3xl p-10 text-white relative overflow-hidden">
                            <div className="absolute -top-20 -right-20 w-40 h-40 bg-accent/20 rounded-full blur-3xl pointer-events-none"></div>
                            <h3 className="text-xl font-heading font-bold text-white mb-6">Support Services Include</h3>
                            <ul className="space-y-3">{["On-site technical troubleshooting", "Equipment setup & configuration", "Hardware diagnostics & repair", "System maintenance programs", "IT consulting & advice", "Emergency technical support"].map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-200"><CheckCircle2 className="w-5 h-5 text-accent shrink-0" /> {item}</li>))}</ul>
                        </div>
                    </div>
                </section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Our Technical Support Services</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{[{ icon: Settings, title: "Equipment Setup & Configuration", items: ["Printer & scanner installation", "Projector & display setup", "Access control system configuration", "Audiovisual equipment setup"] }, { icon: Wrench, title: "Hardware Diagnostics & Repair", items: ["Computer hardware repair", "Peripheral device troubleshooting", "Component replacement", "Performance optimization"] }, { icon: Headphones, title: "On-Site Technical Support", items: ["Same-day on-site visits", "Office technical assistance", "Home technical support", "Commercial facility support"] }, { icon: HelpCircle, title: "Maintenance & Contracts", items: ["Scheduled maintenance visits", "Monthly support packages", "Annual maintenance agreements", "Priority response contracts"] }].map((s, idx) => (<div key={idx} className="bg-background rounded-3xl p-8 border border-borderGrey"><div className="flex items-center gap-4 mb-6"><div className="w-12 h-12 rounded-2xl bg-emerald-400/10 flex items-center justify-center text-emerald-400"><s.icon className="w-6 h-6" /></div><h3 className="text-xl font-heading font-bold text-textDark">{s.title}</h3></div><ul className="space-y-2">{s.items.map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-600 font-sans"><CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" /> {item}</li>))}</ul></div>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl text-center"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-6">Technical Support Across Riyadh</h2><p className="text-lg text-gray-600 font-sans max-w-3xl mx-auto mb-10">Our technicians serve all major areas throughout Riyadh:</p><div className="flex flex-wrap justify-center gap-3">{["Olaya", "Al Malaz", "Al Nakheel", "Al Yasmin", "Al Murabba", "King Fahd District", "Al Worood"].map((a, i) => (<span key={i} className="px-4 py-2 bg-accent/10 text-accent rounded-full font-semibold text-sm border border-accent/20">{a}</span>))}</div></div></section>
                <section className="bg-white py-16"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-2xl font-heading font-bold text-textDark mb-8 text-center">Explore Related Services</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[{ title: "Electronics Repair", slug: "electronics-repair", desc: "Device diagnostics and repair." }, { title: "Networking Solutions", slug: "networking-solutions", desc: "IT infrastructure and support." }, { title: "Electrical Services", slug: "electrical-services", desc: "Electrical installation and maintenance." }].map((link, idx) => (<Link key={idx} to={`/services/${link.slug}`} className="flex items-center justify-between p-6 bg-background rounded-2xl border border-borderGrey hover:border-accent/30 transition-colors group"><div><h3 className="font-heading font-bold text-textDark mb-1">{link.title}</h3><p className="text-sm text-gray-500">{link.desc}</p></div><ArrowRight className="w-5 h-5 text-accent opacity-0 group-hover:opacity-100 transition-opacity" /></Link>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-4">{faqData.map((faq, idx) => (<details key={idx} className="bg-white rounded-2xl border border-borderGrey p-6 group"><summary className="font-heading font-bold text-textDark cursor-pointer list-none flex items-center justify-between">{faq.q}<span className="text-accent text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-gray-600 font-sans mt-4 leading-relaxed">{faq.a}</p></details>))}</div></div></section>
                <section className="pb-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><div className="bg-primary rounded-3xl p-10 md:p-16 text-center relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-accent/20 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div><div className="relative z-10 max-w-2xl mx-auto"><h2 className="text-3xl md:text-4xl font-heading font-bold text-white mb-4">Need Technical Assistance in Riyadh?</h2><p className="text-gray-300 font-sans text-lg mb-8">Our team is ready to solve any technical challenge you face.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition-all transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Now</a><a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 font-semibold px-8 py-4 rounded-xl transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5" /> WhatsApp Us</a></div></div></div></div></section>
            </div>
        </>
    );
}
