import { WhatsAppIcon } from '../../components/icons/WhatsAppIcon';
import { SEO } from '../../components/SEO';
import { Link } from 'react-router-dom';
import { PhoneCall, ArrowRight, MapPin, Cpu, Network, Camera, Zap, Wrench, Smartphone } from 'lucide-react';

export default function DubaiLocation() {
    const faqData = [
        { q: "What is Perfect & Clean Edge Solutions?", a: "Perfect & Clean Edge Solutions is our Dubai-based affiliate that extends Perfect Energy Solution's technical services across the UAE and the broader Gulf region." },
        { q: "What services are available in Dubai?", a: "We offer electronics repair, networking solutions, CCTV installation, electrical services, technical support, and SIM card services throughout Dubai and the UAE." },
        { q: "Do you cover all areas in Dubai?", a: "Yes, we serve all major areas in Dubai including Deira, Bur Dubai, Business Bay, Downtown, JLT, DIFC, Al Quoz, and surrounding districts." },
        { q: "How can I contact the Dubai office?", a: "You can reach us via phone at +966 55 670 4985 or through WhatsApp for Dubai inquiries." },
        { q: "Do you provide on-site services in Dubai?", a: "Yes. Our technicians provide on-site technical services across all major Dubai districts and surrounding areas in the UAE." }
    ];
    const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqData.map(f => ({ "@type": "Question", "name": f.q, "acceptedAnswer": { "@type": "Answer", "text": f.a } })) };

    return (
        <>
            <SEO title="Technical Services in Dubai | Perfect & Clean Edge Solutions" description="Professional electronics repair, networking, CCTV, and electrical services in Dubai. Perfect & Clean Edge Solutions — your trusted technical partner in the UAE." canonicalUrl="/locations/dubai"
                jsonLdSchema={[faqSchema, { "@context": "https://schema.org", "@type": "LocalBusiness", "name": "Perfect & Clean Edge Solutions - Dubai", "address": { "@type": "PostalAddress", "addressLocality": "Dubai", "addressRegion": "Dubai", "addressCountry": "AE" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://perfectenergysolution.com" }, { "@type": "ListItem", "position": 2, "name": "Locations", "item": "https://perfectenergysolution.com/locations" }, { "@type": "ListItem", "position": 3, "name": "Dubai" }] }]} />
            <div className="flex flex-col min-h-screen bg-background">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl pt-8"><nav className="flex items-center gap-2 text-sm text-gray-500 font-sans"><Link to="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link to="/locations" className="hover:text-accent transition-colors">Locations</Link><span>/</span><span className="text-textDark font-medium">Dubai</span></nav></div>
                <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-12 lg:py-16">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-sm font-medium mb-6"><MapPin className="w-4 h-4" /> Regional Support — UAE</div>
                            <h1 className="text-4xl md:text-5xl font-heading font-extrabold text-textDark leading-tight mb-6">Technical Services in <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-accent">Dubai, UAE</span></h1>
                            <p className="text-lg text-textDark/70 font-sans leading-relaxed mb-4">Perfect & Clean Edge Solutions is our Dubai-based affiliate, extending Perfect Energy Solution's professional technical services across the United Arab Emirates. We deliver electronics repair, networking solutions, CCTV installation, electrical services, and SIM card services for homes, offices, and commercial facilities throughout Dubai.</p>
                            <p className="text-base text-gray-500 font-sans leading-relaxed mb-8">With dedicated technicians serving all major districts in Dubai — from Deira and Business Bay to JLT and Al Quoz — we provide the same reliable, expert-level technical support that has made Perfect Energy Solution a trusted name across the Gulf region.</p>
                            <div className="flex flex-col sm:flex-row gap-4">
                                <a href="tel:+966556704985" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-semibold transition-all shadow-lg transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Dubai Office</a>
                                <a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white hover:bg-gray-50 text-primary border border-borderGrey px-8 py-4 rounded-xl font-semibold transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5 text-green-500" /> WhatsApp Us</a>
                            </div>
                        </div>
                        <div className="rounded-3xl overflow-hidden shadow-2xl">
                            <img src="/Perfect Energy Solution Dubai.webp" alt="Perfect and Clean Edge Solutions Dubai office" loading="lazy" className="w-full h-full object-cover min-h-[350px]" />
                        </div>
                    </div>
                </section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Services Available in Dubai</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{[{ icon: Cpu, title: "Electronics Repair", slug: "electronics-repair", desc: "Device repair, component replacement, and electronic maintenance." }, { icon: Network, title: "Networking Solutions", slug: "networking-solutions", desc: "Office network setup, IT support, and infrastructure." }, { icon: Camera, title: "CCTV Installation", slug: "cctv-installation", desc: "Security camera systems and surveillance setup." }, { icon: Zap, title: "Electrical Services", slug: "electrical-services", desc: "Electrical installation, wiring, and maintenance." }, { icon: Wrench, title: "Technical Support", slug: "technical-support", desc: "On-site troubleshooting and IT assistance." }, { icon: Smartphone, title: "SIM Card Services", slug: "sim-card-services", desc: "SIM activation, recharge, and mobile plans." }].map((s, idx) => (<Link key={idx} to={`/services/${s.slug}`} className="bg-background rounded-3xl p-8 border border-borderGrey hover:shadow-lg transition-all group block"><div className="flex items-center gap-4 mb-4"><div className="w-12 h-12 rounded-2xl bg-accent/10 flex items-center justify-center text-accent group-hover:scale-110 transition-transform"><s.icon className="w-6 h-6" /></div><h3 className="text-lg font-heading font-bold text-textDark">{s.title}</h3></div><p className="text-gray-600 font-sans text-sm leading-relaxed">{s.desc}</p><span className="inline-flex items-center gap-1 text-accent font-semibold mt-4 text-sm group-hover:gap-2 transition-all">View Details <ArrowRight className="w-4 h-4" /></span></Link>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl text-center"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-6">Areas We Cover in Dubai</h2><p className="text-lg text-gray-600 font-sans max-w-3xl mx-auto mb-10 leading-relaxed">Our technicians serve all major districts across Dubai and surrounding areas.</p><div className="flex flex-wrap justify-center gap-3">{["Deira", "Bur Dubai", "Business Bay", "Downtown Dubai", "JLT", "DIFC", "Al Quoz", "Jumeirah", "Dubai Marina", "Silicon Oasis", "Al Barsha", "International City"].map((area, idx) => (<span key={idx} className="px-5 py-2.5 bg-accent/10 text-accent rounded-full font-semibold text-sm border border-accent/20">{area}</span>))}</div></div></section>
                <section className="bg-white py-16"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-2xl font-heading font-bold text-textDark mb-8 text-center">Our Other Locations</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{[{ title: "Riyadh — Headquarters", slug: "riyadh", desc: "Primary service center in Saudi Arabia." }, { title: "Kochi — Regional Support", slug: "kochi", desc: "Regional coordination and support center." }].map((link, idx) => (<Link key={idx} to={`/locations/${link.slug}`} className="flex items-center justify-between p-6 bg-background rounded-2xl border border-borderGrey hover:border-accent/30 transition-colors group"><div><h3 className="font-heading font-bold text-textDark mb-1">{link.title}</h3><p className="text-sm text-gray-500">{link.desc}</p></div><ArrowRight className="w-5 h-5 text-accent opacity-0 group-hover:opacity-100 transition-opacity" /></Link>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-4">{faqData.map((faq, idx) => (<details key={idx} className="bg-background rounded-2xl border border-borderGrey p-6 group"><summary className="font-heading font-bold text-textDark cursor-pointer list-none flex items-center justify-between">{faq.q}<span className="text-accent text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-gray-600 font-sans mt-4 leading-relaxed">{faq.a}</p></details>))}</div></div></section>
                <section className="pb-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><div className="bg-primary rounded-3xl p-10 md:p-16 text-center relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-accent/20 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div><div className="relative z-10 max-w-2xl mx-auto"><h2 className="text-3xl md:text-4xl font-heading font-bold text-white mb-4">Need Technical Services in Dubai?</h2><p className="text-gray-300 font-sans text-lg mb-8">Our Dubai team is ready to help with any technical project.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="tel:+966556704985" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition-all transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Now</a><a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 font-semibold px-8 py-4 rounded-xl transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5" /> WhatsApp Us</a></div></div></div></div></section>
            </div>
        </>
    );
}
