import { WhatsAppIcon } from '../../components/icons/WhatsAppIcon';
import { SEO } from '../../components/SEO';
import { Link } from 'react-router-dom';
import { CheckCircle2, PhoneCall, ArrowRight, MapPin } from 'lucide-react';

export default function KochiLocation() {
    const faqData = [
        { q: "What services does Perfect Energy Solution offer from Kochi?", a: "Our Kochi office provides regional coordination, technical resource support, procurement assistance, and client relationship management for our operations in the Gulf region." },
        { q: "Does Kochi handle direct service delivery?", a: "Kochi primarily serves as a regional support center. Direct service delivery is coordinated through our Riyadh headquarters and Dubai office." },
        { q: "How can I contact the Kochi office?", a: "You can reach us via phone at +966 55 670 4985 or through WhatsApp. Our Kochi team will route your inquiry to the appropriate department." },
        { q: "What are the Kochi office working hours?", a: "Our Kochi office operates Monday to Saturday, 9:00 AM – 6:00 PM IST." }
    ];
    const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqData.map(f => ({ "@type": "Question", "name": f.q, "acceptedAnswer": { "@type": "Answer", "text": f.a } })) };

    return (
        <>
            <SEO title="Perfect Energy Solution Kochi | Regional Support Center" description="Perfect Energy Solution Kochi regional support center. Providing coordination, procurement, and technical resource support for our Gulf region operations." canonicalUrl="/locations/kochi"
                jsonLdSchema={[faqSchema, { "@context": "https://schema.org", "@type": "LocalBusiness", "name": "Perfect Energy Solution - Kochi", "address": { "@type": "PostalAddress", "addressLocality": "Kochi", "addressRegion": "Kerala", "addressCountry": "IN" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://perfectenergysolution.com" }, { "@type": "ListItem", "position": 2, "name": "Locations", "item": "https://perfectenergysolution.com/locations" }, { "@type": "ListItem", "position": 3, "name": "Kochi" }] }]} />
            <div className="flex flex-col min-h-screen bg-background">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl pt-8"><nav className="flex items-center gap-2 text-sm text-gray-500 font-sans"><Link to="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link to="/locations" className="hover:text-accent transition-colors">Locations</Link><span>/</span><span className="text-textDark font-medium">Kochi</span></nav></div>
                <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-12 lg:py-16">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-sm font-medium mb-6"><MapPin className="w-4 h-4" /> Regional Support</div>
                            <h1 className="text-4xl md:text-5xl font-heading font-extrabold text-textDark leading-tight mb-6">Perfect Energy Solution <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-accent">Kochi</span></h1>
                            <p className="text-lg text-textDark/70 font-sans leading-relaxed mb-4">Our Kochi office serves as a vital regional support center for Perfect Energy Solution, providing coordination, technical resources, procurement assistance, and client management support for our operations across the Gulf region and the Indian subcontinent.</p>
                            <p className="text-base text-gray-500 font-sans leading-relaxed mb-8">Located in the vibrant commercial hub of Kochi, Kerala, this office enables us to maintain strong supply chain connections, recruit skilled technical professionals, and provide seamless support to our clients in Riyadh and the UAE.</p>
                            <div className="flex flex-col sm:flex-row gap-4">
                                <a href="tel:+966556704985" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-semibold transition-all shadow-lg transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Contact Us</a>
                                <a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white hover:bg-gray-50 text-primary border border-borderGrey px-8 py-4 rounded-xl font-semibold transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5 text-green-500" /> WhatsApp</a>
                            </div>
                        </div>
                        <div className="rounded-3xl overflow-hidden shadow-2xl">
                            <img src="/Perfect Energy Solution Kochi.jpg" alt="Perfect Energy Solution Kochi regional support center" loading="lazy" className="w-full h-full object-cover min-h-[350px]" />
                        </div>
                    </div>
                </section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">What Kochi Supports</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{[{ title: "Regional Coordination", items: ["Client relationship management", "Project coordination", "Communication hub for Gulf operations", "Quality oversight"] }, { title: "Technical Resources", items: ["Skilled technician recruitment", "Technical training programs", "Resource allocation", "Knowledge management"] }, { title: "Procurement & Supply Chain", items: ["Component sourcing", "Vendor management", "Quality assurance", "Inventory coordination"] }, { title: "Administrative Support", items: ["Documentation & compliance", "Financial coordination", "HR & recruitment support", "Reporting & analytics"] }].map((s, idx) => (<div key={idx} className="bg-background rounded-3xl p-8 border border-borderGrey"><h3 className="text-xl font-heading font-bold text-textDark mb-4">{s.title}</h3><ul className="space-y-2">{s.items.map((item, i) => (<li key={i} className="flex items-center gap-3 text-gray-600 font-sans"><CheckCircle2 className="w-4 h-4 text-accent shrink-0" /> {item}</li>))}</ul></div>))}</div></div></section>
                <section className="py-16"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-2xl font-heading font-bold text-textDark mb-8 text-center">Our Other Locations</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{[{ title: "Riyadh — Headquarters", slug: "riyadh", desc: "Primary service center in Riyadh." }, { title: "Dubai — Regional Support", slug: "dubai", desc: "Perfect & Clean Edge Solutions in the UAE." }].map((link, idx) => (<Link key={idx} to={`/locations/${link.slug}`} className="flex items-center justify-between p-6 bg-background rounded-2xl border border-borderGrey hover:border-accent/30 transition-colors group"><div><h3 className="font-heading font-bold text-textDark mb-1">{link.title}</h3><p className="text-sm text-gray-500">{link.desc}</p></div><ArrowRight className="w-5 h-5 text-accent opacity-0 group-hover:opacity-100 transition-opacity" /></Link>))}</div></div></section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-4">{faqData.map((faq, idx) => (<details key={idx} className="bg-background rounded-2xl border border-borderGrey p-6 group"><summary className="font-heading font-bold text-textDark cursor-pointer list-none flex items-center justify-between">{faq.q}<span className="text-accent text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-gray-600 font-sans mt-4 leading-relaxed">{faq.a}</p></details>))}</div></div></section>
                <section className="pb-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><div className="bg-primary rounded-3xl p-10 md:p-16 text-center relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-accent/20 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div><div className="relative z-10 max-w-2xl mx-auto"><h2 className="text-3xl md:text-4xl font-heading font-bold text-white mb-4">Get in Touch</h2><p className="text-gray-300 font-sans text-lg mb-8">Contact our Kochi support center for any inquiries.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="tel:+966556704985" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition-all transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Now</a><a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 font-semibold px-8 py-4 rounded-xl transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5" /> WhatsApp</a></div></div></div></div></section>
            </div>
        </>
    );
}
