import { WhatsAppIcon } from '../../components/icons/WhatsAppIcon';
import { SEO } from '../../components/SEO';
import { Link } from 'react-router-dom';
import { PhoneCall, ArrowRight, MapPin, Cpu, Network, Camera, Zap, Wrench, Sun } from 'lucide-react';

export default function RiyadhLocation() {
    const faqData = [
        { q: "Where is Perfect Energy Solution located in Riyadh?", a: "Our headquarters is centrally located in Riyadh, providing easy access for clients across all major districts. Contact us for our exact location and directions." },
        { q: "What services do you offer in Riyadh?", a: "We offer electronics repair, networking solutions, CCTV installation, electrical services, technical support, and solar energy solutions across Riyadh." },
        { q: "Do you provide on-site services in Riyadh?", a: "Yes. Our technicians provide on-site services across all major Riyadh districts including Olaya, Al Malaz, Al Nakheel, Al Yasmin, and more." },
        { q: "What are your working hours?", a: "We operate Saturday to Thursday, 9:00 AM – 6:00 PM. Emergency services may be available outside regular hours." },
        { q: "How can I contact Perfect Energy Solution in Riyadh?", a: "You can reach us via phone at +966 56 614 9219, WhatsApp, or by visiting our office in Riyadh." }
    ];
    const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqData.map(f => ({ "@type": "Question", "name": f.q, "acceptedAnswer": { "@type": "Answer", "text": f.a } })) };

    return (
        <>
            <SEO title="Technical Services in Riyadh | Perfect Energy Solution Headquarters" description="Perfect Energy Solution Riyadh headquarters. Professional electronics repair, networking, CCTV installation, and electrical services across all Riyadh districts." canonicalUrl="/locations/riyadh"
                jsonLdSchema={[faqSchema, { "@context": "https://schema.org", "@type": "LocalBusiness", "name": "Perfect Energy Solution - Riyadh", "address": { "@type": "PostalAddress", "addressLocality": "Riyadh", "addressRegion": "Riyadh Province", "addressCountry": "SA" }, "telephone": "+966566149219", "openingHours": "Sa-Th 09:00-18:00" }, { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://perfectenergysolution.com" }, { "@type": "ListItem", "position": 2, "name": "Locations", "item": "https://perfectenergysolution.com/locations" }, { "@type": "ListItem", "position": 3, "name": "Riyadh" }] }]} />
            <div className="flex flex-col min-h-screen bg-background">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl pt-8"><nav className="flex items-center gap-2 text-sm text-gray-500 font-sans"><Link to="/" className="hover:text-accent transition-colors">Home</Link><span>/</span><Link to="/locations" className="hover:text-accent transition-colors">Locations</Link><span>/</span><span className="text-textDark font-medium">Riyadh</span></nav></div>
                <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-12 lg:py-16">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-sm font-medium mb-6"><MapPin className="w-4 h-4" /> Primary Headquarters</div>
                            <h1 className="text-4xl md:text-5xl font-heading font-extrabold text-textDark leading-tight mb-6">Technical Services in <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-accent">Riyadh, Saudi Arabia</span></h1>
                            <p className="text-lg text-textDark/70 font-sans leading-relaxed mb-4">Perfect Energy Solution's Riyadh office is our primary headquarters and main service center, delivering professional electronics repair, networking solutions, CCTV installation, electrical services, and solar energy solutions across all major districts in the Saudi capital.</p>
                            <p className="text-base text-gray-500 font-sans leading-relaxed mb-8">With over 15 years of experience serving Riyadh's residential customers, small businesses, offices, and commercial facilities, we have built a reputation for reliability, technical expertise, and excellent customer service throughout the Kingdom.</p>
                            <div className="flex flex-col sm:flex-row gap-4">
                                <a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-semibold transition-all shadow-lg transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Riyadh Office</a>
                                <a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white hover:bg-gray-50 text-primary border border-borderGrey px-8 py-4 rounded-xl font-semibold transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5 text-green-500" /> WhatsApp Us</a>
                            </div>
                        </div>
                        <div className="rounded-3xl overflow-hidden shadow-2xl">
                            <img src="/Perfect Energy Solution RIyadh.webp" alt="Perfect Energy Solution office in Riyadh Saudi Arabia" loading="lazy" className="w-full h-full object-cover min-h-[350px]" />
                        </div>
                    </div>
                </section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Services Available in Riyadh</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{[{ icon: Cpu, title: "Electronics Repair", slug: "electronics-repair", desc: "Device repair, component replacement, and electronic maintenance." }, { icon: Network, title: "Networking Solutions", slug: "networking-solutions", desc: "Office network setup, IT support, and infrastructure." }, { icon: Camera, title: "CCTV Installation", slug: "cctv-installation", desc: "Security camera systems and surveillance setup." }, { icon: Zap, title: "Electrical Services", slug: "electrical-services", desc: "Electrical installation, wiring, and maintenance." }, { icon: Wrench, title: "Technical Support", slug: "technical-support", desc: "On-site troubleshooting and IT assistance." }, { icon: Sun, title: "Solar Solutions", slug: "solar-solutions", desc: "Solar panel installation and energy management." }].map((s, idx) => (<Link key={idx} to={`/services/${s.slug}`} className="bg-background rounded-3xl p-8 border border-borderGrey hover:shadow-lg transition-all group block"><div className="flex items-center gap-4 mb-4"><div className="w-12 h-12 rounded-2xl bg-accent/10 flex items-center justify-center text-accent group-hover:scale-110 transition-transform"><s.icon className="w-6 h-6" /></div><h3 className="text-lg font-heading font-bold text-textDark">{s.title}</h3></div><p className="text-gray-600 font-sans text-sm leading-relaxed">{s.desc}</p><span className="inline-flex items-center gap-1 text-accent font-semibold mt-4 text-sm group-hover:gap-2 transition-all">View Details <ArrowRight className="w-4 h-4" /></span></Link>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl text-center"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-6">Areas We Cover in Riyadh</h2><p className="text-lg text-gray-600 font-sans max-w-3xl mx-auto mb-10 leading-relaxed">Our technicians provide on-site and in-shop services across all major districts in Riyadh, ensuring fast response times and convenient access for our clients.</p><div className="flex flex-wrap justify-center gap-3">{["Olaya", "Al Malaz", "Al Nakheel", "Al Yasmin", "Al Murabba", "Al Rawdah", "Al Sulimaniyah", "King Fahd District", "Al Worood", "Exit 5 Area", "Al Qurtubah", "Al Hamra"].map((area, idx) => (<span key={idx} className="px-5 py-2.5 bg-accent/10 text-accent rounded-full font-semibold text-sm border border-accent/20">{area}</span>))}</div></div></section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl font-heading font-extrabold text-textDark mb-12 text-center">Trusted by Riyadh Since 2010</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">{[{ value: "15+", label: "Years Experience" }, { value: "5000+", label: "Projects Completed" }, { value: "98%", label: "Client Satisfaction" }, { value: "24-72h", label: "Avg. Turnaround" }].map((s, i) => (<div key={i} className="bg-background rounded-3xl p-8 border border-borderGrey shadow-sm"><div className="text-3xl font-heading font-bold text-accent mb-2">{s.value}</div><div className="text-gray-600 font-sans text-sm">{s.label}</div></div>))}</div></div></section>
                <section className="py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><h2 className="text-3xl font-heading font-extrabold text-textDark mb-8 text-center">Contact Information</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{[{ label: "Phone", value: "+966 56 614 9219", href: "tel:+966566149219", icon: PhoneCall }, { label: "WhatsApp", value: "Chat with us", href: "https://wa.me/966566149219", icon: WhatsAppIcon }, { label: "Location", value: "View on Google Maps", href: "https://maps.app.goo.gl/mJXH2CsENMQ7byXd8", icon: MapPin }].map((c, i) => (<a key={i} href={c.href} target={c.href.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className="bg-white rounded-3xl p-8 border border-borderGrey text-center hover:shadow-md transition-all block group"><div className="w-16 h-16 rounded-2xl bg-accent/10 flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform"><c.icon className="w-8 h-8 text-accent" /></div><div className="text-sm text-gray-500 mb-1">{c.label}</div><div className="font-heading font-bold text-textDark">{c.value}</div></a>))}</div></div></section>
                <section className="bg-white py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-3xl md:text-4xl font-heading font-extrabold text-textDark mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-4">{faqData.map((faq, idx) => (<details key={idx} className="bg-background rounded-2xl border border-borderGrey p-6 group"><summary className="font-heading font-bold text-textDark cursor-pointer list-none flex items-center justify-between">{faq.q}<span className="text-accent text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-gray-600 font-sans mt-4 leading-relaxed">{faq.a}</p></details>))}</div></div></section>
                <section className="pb-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl"><div className="bg-primary rounded-3xl p-10 md:p-16 text-center relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-accent/20 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div><div className="relative z-10 max-w-2xl mx-auto"><h2 className="text-3xl md:text-4xl font-heading font-bold text-white mb-4">Need Technical Services in Riyadh?</h2><p className="text-gray-300 font-sans text-lg mb-8">Contact our Riyadh headquarters today for a free consultation.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="tel:+966566149219" className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-emerald-500 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition-all transform hover:-translate-y-1"><PhoneCall className="w-5 h-5" /> Call Now</a><a href="https://wa.me/966566149219" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white backdrop-blur-md border border-white/20 font-semibold px-8 py-4 rounded-xl transition-all transform hover:-translate-y-1"><WhatsAppIcon className="w-5 h-5" /> WhatsApp Us</a></div></div></div></div></section>
            </div>
        </>
    );
}
